# Generated by Django 4.1.4 on 2022-12-29 05:41

from django.db import migrations, models
import restapi.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=50, validators=[restapi.models.validateCategory])),
            ],
        ),
    ]
