# Generated by Django 4.1.4 on 2022-12-31 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_prompt_rubric_skill_mentortext'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentortext',
            name='createdOn',
            field=models.DateField(null=True),
        ),
    ]
